stages:
  - lint
  - test
  - release
variables:
  GIT_SSL_NO_VERIFY: "true"
lint:
  stage: lint
  tags:
    - powershell
  script:
    - $results = Invoke-ScriptAnalyzer .\functions\; $results; exit $results.count
test:
  stage: test
  tags: 
   - powershell
   - pester
  script:
   - Invoke-Pester -EnableExit -CodeCoverage .\functions\*.ps1
  except:
    - master
release:
  stage: release
  tags:
   - powershell
   - psgallery
  script:
   - Invoke-PSDeploy
  only:
    - master
  when: manual